/**
 * analyst-fixtures-catalog.ts — Data source catalog fixture (8 sources).
 */
import type { CatalogSource } from "./analyst-fixtures-types";

export const analystCatalogFixture: CatalogSource[] = [
  {
    id: "sensor",
    name: "VL53L1X distance sensor",
    kind: "serial",
    location: "COM3 @ 115200 baud",
    fields: [
      { name: "mm", type: "u16" },
      { name: "cm", type: "u8" },
      { name: "timestamp", type: "ISO 8601" },
    ],
    retention: "stream (not persisted)",
    rowCount: 0,
    bytes: 0,
  },
  {
    id: "sessions",
    name: "Session history",
    kind: "sqlite",
    location: "{app_data}/desk.db :: sessions",
    fields: [
      { name: "id", type: "INTEGER PK" },
      { name: "started_at", type: "TEXT" },
      { name: "ended_at", type: "TEXT" },
      { name: "state", type: "TEXT" },
      { name: "duration_seconds", type: "INTEGER" },
      { name: "sitting_seconds", type: "INTEGER" },
      { name: "standing_seconds", type: "INTEGER" },
      { name: "position_changes", type: "INTEGER" },
      { name: "session_limit_secs", type: "INTEGER" },
      { name: "date_local", type: "TEXT" },
    ],
    retention: "no limit",
    rowCount: 312,
    bytes: 48_320,
  },
  {
    id: "snapshots",
    name: "Minute snapshots",
    kind: "json",
    location: "{app_data}/logs/YYYY-MM-DD/HH-MM.json",
    fields: [
      { name: "ts", type: "ISO 8601" },
      { name: "state", type: "DeskState" },
      { name: "sitting_seconds", type: "u32" },
      { name: "standing_seconds", type: "u32" },
      { name: "desk_height_cm", type: "u8" },
      { name: "idle_secs", type: "u32" },
      { name: "score", type: "i32" },
    ],
    retention: "7 days",
    rowCount: 10_080,
    bytes: 5_040_000,
  },
  {
    id: "events",
    name: "Event log",
    kind: "events",
    location: "{app_data}/logs/YYYY-MM-DD/events.log",
    fields: [
      { name: "ts", type: "HH:MM:SS" },
      { name: "type", type: "STATE | CREDIT | NOTIF | DEVICE | ALERT | RESET" },
      { name: "details", type: "TEXT" },
    ],
    retention: "7 days",
    rowCount: 1_421,
    bytes: 89_440,
  },
  {
    id: "profiles-ergo",
    name: "Ergonomic profiles",
    kind: "file",
    location: "{app_data}/profiles/ergonomic/*.json",
    fields: [
      { name: "id", type: "TEXT" },
      { name: "session_limit_secs", type: "u32" },
      { name: "break_credit_multiplier", type: "f32" },
    ],
    retention: "persistent",
    rowCount: 4,
    bytes: 6_120,
  },
  {
    id: "profiles-comm",
    name: "Communication profiles",
    kind: "file",
    location: "{app_data}/profiles/communication/*.json",
    fields: [
      { name: "id", type: "TEXT" },
      { name: "snooze.notify_cooldowns_secs", type: "u32[]" },
      { name: "escalation.steps", type: "Step[]" },
    ],
    retention: "persistent",
    rowCount: 5,
    bytes: 8_640,
  },
  {
    id: "store",
    name: "Settings store",
    kind: "store",
    location: "tauri-plugin-store :: settings.json",
    fields: [
      { name: "sitting_mm", type: "u16" },
      { name: "standing_mm", type: "u16" },
      { name: "desk_thickness_mm", type: "u16" },
      { name: "active_ergonomic_profile", type: "TEXT" },
    ],
    retention: "persistent",
    rowCount: 9,
    bytes: 612,
  },
  {
    id: "system",
    name: "System idle signals",
    kind: "signal",
    location: "Win32 GetLastInputInfo()",
    fields: [
      { name: "idle_secs", type: "u32" },
      { name: "away_bout_secs", type: "u32" },
    ],
    retention: "in-memory",
    rowCount: 0,
    bytes: 0,
  },
];
