import { lstat, mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const safeId = /^[a-z0-9][a-z0-9-]*$/;

async function ensureRealDirectory(path) {
  try {
    const entry = await lstat(path);
    if (!entry.isDirectory() || entry.isSymbolicLink()) {
      throw new Error(`Generated output path is not a real directory: ${path}`);
    }
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
    await mkdir(path);
  }
}

export function previewManifestSource(families) {
  return `// Generated by generate.mjs from manifest.mjs.\nwindow.iconStudioFamilies = ${JSON.stringify(families, null, 2)};\n`;
}

export async function writeIconSet(root, families, renderers) {
  if (!Array.isArray(families) || families.length === 0) {
    throw new Error('Icon manifest must contain at least one family');
  }

  // Render and validate everything before changing output. Family directories
  // are generator-owned; only their immediate SVG files are removed as stale.
  const rendered = [];
  const familyIds = new Set();
  for (const family of families) {
    if (!safeId.test(family.id) || familyIds.has(family.id)) {
      throw new Error(`Invalid or duplicate icon family: ${family.id}`);
    }
    familyIds.add(family.id);
    if (!Array.isArray(family.names) || family.names.length === 0 || typeof renderers[family.id] !== 'function') {
      throw new Error(`Missing names or renderer for icon family: ${family.id}`);
    }
    const names = new Set();
    const icons = [];
    for (const name of family.names) {
      if (!safeId.test(name) || names.has(name)) {
        throw new Error(`Invalid or duplicate icon name in ${family.id}: ${name}`);
      }
      names.add(name);
      const svg = renderers[family.id](name);
      if (typeof svg !== 'string' || !svg.startsWith('<svg ') || !svg.includes('</svg>')) {
        throw new Error(`Renderer returned invalid SVG for ${family.id}/${name}`);
      }
      icons.push({ name, svg });
    }
    rendered.push({ id: family.id, icons, names });
  }

  const iconsRoot = join(root, 'icons');
  await ensureRealDirectory(iconsRoot);
  for (const family of rendered) {
    const out = join(iconsRoot, family.id);
    await ensureRealDirectory(out);
    for (const { name, svg } of family.icons) {
      await writeFile(join(out, `${name}.svg`), svg, 'utf8');
    }
    for (const entry of await readdir(out, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith('.svg') && !family.names.has(entry.name.slice(0, -4))) {
        await rm(join(out, entry.name));
      }
    }
  }
  await writeFile(join(root, 'preview-manifest.js'), previewManifestSource(families), 'utf8');
}
