//! voice_ai.rs — optional AI reply to a dictated voice note (BYOK OpenRouter).
//!
//! The phone's voice capture already works without this module: an intent is
//! parsed locally and acknowledged locally. This adds one short coaching
//! sentence on top, generated by whichever OpenRouter model the user pays
//! for. Everything here is therefore *optional by construction* — a missing
//! key is "not configured", never an error.
//!
//! ## Bring your own key
//! The key comes from [`API_KEY_ENV`] and never from the config store, so it
//! is not written to disk by this app and never crosses the IPC boundary to
//! the frontend. It is never logged either.
//!
//! ## Model
//! `AppConfig.voice_ai_model` when the user picked one, otherwise
//! [`DEFAULT_MODEL`] — the cheap default named in the `openrouter` skill.
//!
//! ## Wiring
//! Nothing calls this yet; the `POST /display/voice` route (E021-T06) is the
//! only intended caller. Keeping it standalone means the route can ship with
//! or without an AI reply and behave the same.

use crate::session::SessionStateDto;
use serde::Deserialize;
use std::time::Duration;

/// Environment variable holding the user's OpenRouter key.
pub const API_KEY_ENV: &str = "OPENROUTER_API_KEY";

/// Cheap default when the user has not picked a model.
pub const DEFAULT_MODEL: &str = "google/gemini-2.5-flash-lite";

/// Production endpoint. Overridable via [`VoiceAi::at_endpoint`] in tests.
const DEFAULT_ENDPOINT: &str = "https://openrouter.ai/api/v1/chat/completions";

/// One request, one timeout. The caller is an HTTP handler the phone is
/// waiting on, so this is deliberately shorter than the webhook's budget.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(8);

/// The whole instruction set. Fixed in code, not configurable: a
/// user-editable system prompt turns an ergonomics coach into a general
/// chatbot with the user's key attached to the bill.
pub const SYSTEM_PROMPT: &str = concat!(
    "You are the voice of a sit/stand desk ergonomics app. ",
    "The user dictated a short note; reply with encouragement or one ",
    "practical ergonomics suggestion grounded in the session numbers given. ",
    "Reply in the same language as the note (Polish or English). ",
    "Answer in at most 60 words, plain sentences, no lists, no markdown. ",
    "Only discuss posture, movement, breaks and the desk session. ",
    "If the note is about anything else, say briefly that you only help with ",
    "desk ergonomics."
);

/// Why a reply could not be produced. `Rejected` is the user's problem (bad
/// key, no credit); the rest are the network's.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VoiceAiError {
    /// Timed out, connection refused, DNS failure.
    Transport,
    /// 4xx — invalid key, no credit, unknown model.
    Rejected(u16),
    /// 5xx — upstream trouble.
    Server(u16),
    /// 2xx whose body was not the expected chat-completion shape.
    Malformed,
}

/// A configured OpenRouter chat client.
pub struct VoiceAi {
    api_key: String,
    model: String,
    endpoint: String,
    http: reqwest::Client,
    timeout: Duration,
}

/// The slice of the chat-completions response we read.
#[derive(Deserialize)]
struct ChatResponse {
    #[serde(default)]
    choices: Vec<ChatChoice>,
}

#[derive(Deserialize)]
struct ChatChoice {
    #[serde(default)]
    message: ChatMessage,
}

#[derive(Deserialize, Default)]
struct ChatMessage {
    #[serde(default)]
    content: String,
}

impl VoiceAi {
    /// Reads the key from [`API_KEY_ENV`] and takes the model from
    /// `AppConfig.voice_ai_model`, falling back to [`DEFAULT_MODEL`].
    ///
    /// Returns `None` — "the user did not bring a key" — rather than an
    /// error, so callers can treat AI replies as an optional extra.
    pub fn from_env(config_model: Option<&str>) -> Option<Self> {
        let api_key = std::env::var(API_KEY_ENV)
            .ok()
            .map(|k| k.trim().to_string())
            .filter(|k| !k.is_empty())?;
        Some(Self {
            api_key,
            model: config_model
                .map(str::trim)
                .filter(|m| !m.is_empty())
                .unwrap_or(DEFAULT_MODEL)
                .to_string(),
            endpoint: DEFAULT_ENDPOINT.to_string(),
            http: reqwest::Client::new(),
            timeout: REQUEST_TIMEOUT,
        })
    }

    /// Builds a client pointed at an explicit endpoint — used by tests to
    /// aim every call at a wiremock server.
    #[cfg_attr(not(test), allow(dead_code))]
    pub fn at_endpoint(api_key: impl Into<String>, model: &str, endpoint: impl Into<String>) -> Self {
        Self {
            api_key: api_key.into(),
            model: model.to_string(),
            endpoint: endpoint.into(),
            http: reqwest::Client::new(),
            timeout: REQUEST_TIMEOUT,
        }
    }

    /// Shortens the request timeout so the timeout path costs a test
    /// milliseconds instead of eight real seconds.
    #[cfg_attr(not(test), allow(dead_code))]
    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    /// Which model this client will ask.
    pub fn model(&self) -> &str {
        &self.model
    }

    /// Asks the model for one short coaching reply to `transcript`.
    ///
    /// `Ok(None)` means "nothing worth saying" — a blank transcript (no
    /// request is made) or a model that answered with empty text. Only a
    /// genuine failure produces `Err`, so a caller may drop the reply and
    /// still acknowledge the note.
    pub async fn reply(
        &self,
        transcript: &str,
        session: &SessionStateDto,
    ) -> Result<Option<String>, VoiceAiError> {
        let transcript = transcript.trim();
        if transcript.is_empty() {
            return Ok(None);
        }

        let body = serde_json::json!({
            "model": self.model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_message(transcript, session)},
            ],
        });

        let response = self
            .http
            .post(&self.endpoint)
            .bearer_auth(&self.api_key)
            .timeout(self.timeout)
            .json(&body)
            .send()
            .await
            .map_err(|_| VoiceAiError::Transport)?;

        let status = response.status();
        if status.is_client_error() {
            return Err(VoiceAiError::Rejected(status.as_u16()));
        }
        if !status.is_success() {
            return Err(VoiceAiError::Server(status.as_u16()));
        }

        let parsed: ChatResponse = response
            .json()
            .await
            .map_err(|_| VoiceAiError::Malformed)?;
        let text = parsed
            .choices
            .first()
            .map(|c| c.message.content.trim().to_string())
            .unwrap_or_default();
        Ok(if text.is_empty() { None } else { Some(text) })
    }
}

/// The user turn: the note itself plus the session numbers the reply may
/// ground itself in. Kept to whole minutes — the model has no use for the
/// second-level precision and it makes the prompt cheaper to read.
fn user_message(transcript: &str, session: &SessionStateDto) -> String {
    format!(
        "Note: {transcript}\n\
         Current state: {state:?}\n\
         Sitting limit used: {used} of {limit} minutes\n\
         Standing today: {standing} minutes\n\
         Position changes today: {changes}\n\
         Daily posture score: {score:.0}",
        state = session.state,
        used = session.limit_used_secs / 60,
        limit = session.session_limit_secs / 60,
        standing = session.standing_seconds / 60,
        changes = session.position_changes,
        score = session.daily_score,
    )
}

// Tests live in voice_ai_tests.rs.
